# Generated by Django 3.0.5 on 2021-05-11 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Page',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=70, verbose_name='Título')),
                ('content', models.TextField(verbose_name='Contenido')),
                ('slug', models.CharField(max_length=150, unique=True, verbose_name='URL')),
                ('visible', models.BooleanField(verbose_name='¿Visible?')),
                ('created_at', models.DateField(auto_now_add=True, verbose_name='Creación')),
                ('updated_at', models.DateField(auto_now=True, verbose_name='Actualización')),
            ],
            options={
                'verbose_name': 'Página',
                'verbose_name_plural': 'Páginas',
            },
        ),
    ]
